#------------------------------------------------------------
# Values for this workshop.
#------------------------------------------------------------

# Which carpentry is this ("swc", "dc", or "lc")?
carpentry: "swc"

# Overall title for pages.
title: "REU-INCLUSION Software Carpentry Workshop"

# Contact email address.
email: lessons@software-carpentry.org

#------------------------------------------------------------
# Generic settings (should not need to change).
#------------------------------------------------------------

# What kind of thing is this ("workshop" or "lesson")?
kind: "workshop"

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: swc-uiuc/2018-05-24-inclusion

# Sites.
amy_site: "https://amy.software-carpentry.org/workshops"
lc_site: "https://librarycarpentry.github.io/"
dc_site: "http://datacarpentry.org"
swc_github: "https://github.com/swcarpentry"
swc_site: "https://software-carpentry.org"
swc_pages: "https://swcarpentry.github.io"
template_repo: "https://github.com/swcarpentry/styles"
example_repo: "https://github.com/swcarpentry/lesson-example"
example_site: "https://swcarpentry.github.com/lesson-example"
workshop_repo: "https://github.com/swc-uiuc/2018-05-24-inclusion"
workshop_site: "https://swcarpentry.github.io/2018-05-24-inclusion"
training_site: "https://swcarpentry.github.io/instructor-training"
swc_installer: "https://github.com/swcarpentry/windows-installer/releases/download/v0.3/SWCarpentryInstaller.exe"

# Surveys.
swc_pre_survey: "https://www.surveymonkey.com/r/swc_pre_workshop_v1?workshop_id=2018-05-24-inclusion"
swc_post_survey: "https://www.surveymonkey.com/r/swc_post_workshop_v1?workshop_id=2018-05-24-inclusion"
dc_pre_survey: "https://www.surveymonkey.com/r/dcpreworkshopassessment?workshop_id=2018-05-24-inclusion"
dc_post_survey: "https://www.surveymonkey.com/r/dcpostworkshopassessment?workshop_id=2018-05-24-inclusion"

# Start time in minutes (0 to be clock-independent, 540 to show a start at 09:00 am)
start_time: 480

# Specify that things in the episodes collection should be output.
collections:
  episodes:
    output: true
    permalink: /:path/index.html
  extras:
    output: true
    permalink: /:path/index.html

# Set the default layout for things in the episodes collection.
defaults:
  - values:
      root: .
  - scope:
      path: ""
      type: episodes
    values:
      layout: episode
      root: ..

# Files and directories that are not to be copied.
exclude:
  - Makefile
  - bin

# Turn off built-in syntax highlighting.
highlighter: false
